<Project>
  <PropertyGroup>
    <!-- Informações e Metadados do Projeto -->
    <Authors>Grupo 5 - MBA DevIO</Authors>
    <Company>MBA DevXpert</Company>
    <Product>Plataforma Educacional</Product>
    <Copyright>Copyright © 2026</Copyright>

    <!-- Versionamento Semântico Centralizado (SemVer) -->
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix Condition="'$(VersionSuffix)' != ''">$(VersionSuffix)</VersionSuffix>

    <!-- Configurações Globais de Compilação C# / .NET 8 -->
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
