// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEducacional.Pagamentos.Api.Data;

#nullable disable

namespace PlataformaEducacional.Pagamentos.Api.Data.Migrations
{
    [DbContext(typeof(PagamentosContext))]
    [Migration("20260324181341_CriacaoDoBancoPagamentos")]
    partial class CriacaoDoBancoPagamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("PlataformaEducacional.Pagamentos.Api.Models.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacional.Pagamentos.Api.Models.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BandeiraCartao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodigoAutorizacao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CustoTransacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataTransacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NSU")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("PagamentoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TID")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PagamentoId");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacional.Pagamentos.Api.Models.Transacao", b =>
                {
                    b.HasOne("PlataformaEducacional.Pagamentos.Api.Models.Pagamento", "Pagamento")
                        .WithMany("Transacoes")
                        .HasForeignKey("PagamentoId")
                        .IsRequired();

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("PlataformaEducacional.Pagamentos.Api.Models.Pagamento", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
