// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEducacional.Alunos.Data;

#nullable disable

namespace PlataformaEducacional.Alunos.Api.Migrations
{
    [DbContext(typeof(AlunosContext))]
    [Migration("20260320175740_AdicionarPedidoIdMatricula")]
    partial class AdicionarPedidoIdMatricula
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CodigoValidacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("MatriculaId")
                        .IsUnique();

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.ProgressoAula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId");

                    b.ToTable("ProgressoAulas");
                });

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.Aluno", b =>
                {
                    b.OwnsOne("PlataformaEducacional.Core.DomainObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("AlunoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("AlunoId");

                            b1.ToTable("Alunos");

                            b1.WithOwner()
                                .HasForeignKey("AlunoId");
                        });

                    b.OwnsOne("PlataformaEducacional.Core.DomainObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AlunoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("AlunoId");

                            b1.ToTable("Alunos");

                            b1.WithOwner()
                                .HasForeignKey("AlunoId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.Certificado", b =>
                {
                    b.HasOne("PlataformaEducacional.Alunos.Domain.Models.Aluno", "Aluno")
                        .WithMany("Certificados")
                        .HasForeignKey("AlunoId")
                        .IsRequired();

                    b.HasOne("PlataformaEducacional.Alunos.Domain.Models.Matricula", "Matricula")
                        .WithOne("Certificado")
                        .HasForeignKey("PlataformaEducacional.Alunos.Domain.Models.Certificado", "MatriculaId")
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.Endereco", b =>
                {
                    b.HasOne("PlataformaEducacional.Alunos.Domain.Models.Aluno", "Aluno")
                        .WithOne("Endereco")
                        .HasForeignKey("PlataformaEducacional.Alunos.Domain.Models.Endereco", "AlunoId")
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.Matricula", b =>
                {
                    b.HasOne("PlataformaEducacional.Alunos.Domain.Models.Aluno", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId")
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.ProgressoAula", b =>
                {
                    b.HasOne("PlataformaEducacional.Alunos.Domain.Models.Matricula", "Matricula")
                        .WithMany("ProgressoAulas")
                        .HasForeignKey("MatriculaId")
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.Aluno", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("PlataformaEducacional.Alunos.Domain.Models.Matricula", b =>
                {
                    b.Navigation("Certificado")
                        .IsRequired();

                    b.Navigation("ProgressoAulas");
                });
#pragma warning restore 612, 618
        }
    }
}
